WITH 차종 AS(
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
      FROM CAR_RENTAL_COMPANY_CAR
     WHERE CAR_TYPE IN ('세단', 'SUV')
)
, 대여중 AS(
    SELECT DISTINCT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE (TO_DATE('2022-11-01', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
            OR TO_DATE('2022-11-30', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE)
)
, 할인정보 AS(
    SELECT CAR_TYPE, 1-(DISCOUNT_RATE / 100) AS 할인
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE CAR_TYPE IN ('세단', 'SUV')
       AND DURATION_TYPE = '30일 이상'
)
SELECT A.CAR_ID
       , A.CAR_TYPE
       , TO_NUMBER(A.DAILY_FEE * 30 * 할인) AS FEE
  FROM 차종 A
       LEFT OUTER JOIN 대여중 B ON A.CAR_ID = B.CAR_ID
       LEFT OUTER JOIN 할인정보 C ON A.CAR_TYPE = C.CAR_TYPE
 WHERE B.CAR_ID IS NULL
   AND TO_NUMBER(A.DAILY_FEE * 30 * 할인) BETWEEN 500000 AND 2000000
ORDER BY TO_NUMBER(A.DAILY_FEE * 30 * 할인) DESC, A.CAR_TYPE, A.CAR_ID DESC;