SELECT CART_ID
  FROM CART_PRODUCTS
 WHERE CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME LIKE 'Milk')
   AND CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME LIKE 'Yogurt')
 GROUP BY CART_ID
ORDER BY CART_ID;