SELECT MONTH
       , CAR_ID
       , COUNT(CAR_ID) AS RECORDS
  FROM (SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH
               , CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
         WHERE CAR_ID IN (SELECT CAR_ID
                            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                           WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-11'
                           GROUP BY CAR_ID 
                            HAVING COUNT(*) >= 5)
           AND TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-11')
 GROUP BY MONTH, CAR_ID
  HAVING COUNT(*) > 0
ORDER BY MONTH, CAR_ID DESC;

