WITH 입양시간 AS(
                SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
                       , COUNT(*) AS COUNT
                  FROM ANIMAL_OUTS
                 GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
)
SELECT A.HOUR
       , CASE WHEN COUNT IS NULL THEN 0 ELSE COUNT END AS COUNT
  FROM (
        SELECT LEVEL - 1 AS HOUR
          FROM DUAL
        CONNECT BY LEVEL <= 24
  ) A
  LEFT OUTER JOIN 입양시간 B
  ON A.HOUR = B.HOUR
  ORDER BY A.HOUR;