SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
  FROM REST_REVIEW R RIGHT OUTER JOIN MEMBER_PROFILE M
                     ON R.MEMBER_ID = M.MEMBER_ID
 WHERE R.MEMBER_ID|| 1 IN (SELECT MEMBER_ID || RANK() OVER(ORDER BY COUNT(*) DESC)
                                          FROM REST_REVIEW
                                         GROUP BY MEMBER_ID)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT