select count(FISH_INFO.FISH_TYPE) as FISH_COUNT, FISH_NAME_INFO.FISH_NAME
from FISH_INFO
inner join FISH_NAME_INFO
        on FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
group by FISH_NAME
order by FISH_COUNT desc;