SELECT PRODUCT.PRODUCT_CODE, (PRODUCT.PRICE * sum(OFFLINE_SALE.SALES_AMOUNT)) as SALES 
from PRODUCT inner join OFFLINE_SALE on PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID 
group by OFFLINE_SALE.PRODUCT_ID having count(OFFLINE_SALE.PRODUCT_ID)
order by SALES desc, PRODUCT.PRODUCT_CODE asc;