SELECT DISTINCT H.CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
 WHERE C.CAR_ID = H.CAR_ID
   AND C.CAR_TYPE IN ('세단')
   AND H.START_DATE >= TO_DATE('2022-10-01', 'YYYY-MM-DD')
ORDER BY H.CAR_ID DESC;